restaurants/favorites/urls.py
from django.urls import path
from .views import list_favorites, add_to_favorites

app_name = 'favorites'
urlpatterns = [
    path('', list_favorites, name='favorites'),
    path('add/', add_to_favorites, name='add_to_favorites'),
]

restaurants/restaurants/urls.py
from django.contrib import admin
from django.urls import path, include
from edit_restaurant_page.views import post_edit
from registration_manager.views import booking_request_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_interface.urls')),
    path('register/', include('registration.urls')),
    path('favorites/', include('favorites.urls')),
    path('booking/', include('booking_request.urls')),
    path('edit/<int:id_place>/', post_edit, name='post_edit'),
    path('booking_request_list/', booking_request_list, name='booking_list')
]

restaurants/user_interface/urls.py
from django.urls import path
from .views import home, restaurant_page, places_list
from .views import SearchResultsView, SearchResultsViewNameStreet


urlpatterns = [
    path('', home, name='home'),
    path('search_result/', SearchResultsView.as_view(), name='search_result'),
    path('<int:id_place>/', restaurant_page, name='restaurant_page'),
    path('places_list/', SearchResultsViewNameStreet.as_view(), name='search_street'),
    path('search_list/', places_list, name='places_list')
]

restaurants/user_interface/models.py
from django.db import models


class TypeKitchen(models.Model):
    id_type = models.IntegerField("Номер типа кухни", primary_key=True)
    name_type = models.CharField("Наименование типа", max_length=64)

    def __str__(self):
        return self.name_type

    class Meta:
        verbose_name = "Тип кухни"
        verbose_name_plural = "Тип кухни"


class TypePlace(models.Model):
    id_type = models.IntegerField("Номер типа заведения", primary_key=True)
    name_type = models.CharField("Наименование типа заведения", max_length=64)

    def __str__(self):
        return self.name_type

    class Meta:
        verbose_name = "Тип заведения"
        verbose_name_plural = "Тип заведения"


class Street(models.Model):
    id_street = models.IntegerField("Код улицы", primary_key=True)
    name_street = models.CharField("Наименование улицы", max_length=64)

    def __str__(self):
        return self.name_street

    class Meta:
        verbose_name = "Улица"
        verbose_name_plural = "Улица"


class Place(models.Model):
    id_place = models.IntegerField("Номер заведения", primary_key=True)
    name_place = models.CharField("Наименование заведения", max_length=64)
    number_phone = models.CharField("Номер телефона", max_length=17, help_text="Формат +*(***)-***-**-**")
    id_street = models.ForeignKey("Street",to_field='id_street', on_delete=models.CASCADE)
    number_buld = models.IntegerField("Номер дома")
    id_type = models.ForeignKey("TypePlace", on_delete=models.CASCADE)
    ##
    operating_mode = models.CharField(max_length=64, null=True)
    live_music = models.BooleanField()
    takeaway_food = models.BooleanField()
    delivery = models.BooleanField()
    summer_veranda = models.BooleanField()
    menu_vegan = models.BooleanField()
    visit_pet = models.BooleanField()
    bus_lunch = models.BooleanField()
    child_room = models.BooleanField()
    features = models.JSONField()
    url = models.SlugField(null=True)

    def __str__(self):
        return self.name_place

    class Meta:
        verbose_name = "Заведения"
        verbose_name_plural = "Заведение"


class Place_typeKitchen(models.Model):
    id = models.IntegerField("Код", primary_key=True)
    id_place = models.ForeignKey("Place",to_field='id_place', on_delete=models.CASCADE)
    id_type = models.ForeignKey("TypeKitchen", to_field='id_type', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = "Заведение_типКухни"
        verbose_name_plural = "Заведение_типКухни"

restaurants/user_interface/forms.py
from django import forms
from .models import Place, TypePlace
from .models import TypeKitchen

class FilterForm(forms.Form):
    type_kitchens = forms.ModelMultipleChoiceField(queryset=TypeKitchen.objects.all(), widget=forms.CheckboxSelectMultiple)

class PlaceFilterForm(forms.Form):
    type_place = forms.ModelMultipleChoiceField(
        queryset=TypePlace.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label='Тип заведения',
        required=False
    )

    def filter_places(self):
        places = Place.objects.all()

        if self.cleaned_data['type_place']:
            places = places.filter(id_type__in=self.cleaned_data['type_place'])

        return places

restaurants/user_interface/views.py
from django.db.models import Q
from django.shortcuts import render
from .models import Place, Street
from .forms import FilterForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    CreateView
)
from .forms import PlaceFilterForm


def place_list(request):
    if request.method == 'POST':
        form = FilterForm(request.POST)
        if form.is_valid():
            type_kitchens = form.cleaned_data['type_kitchens']
            places = Place.objects.filter(place_typekitchen__id_type__in=type_kitchens).distinct()
    else:
        form = FilterForm()
        places = Place.objects.all()
    return render(request, 'place_list.html', {'places': places, 'form': form})


class SearchResultsView(ListView):
    model = Place
    template_name = 'user_interface/search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Place.objects.filter(
            Q(name_place__icontains=query)
        )
        return object_list


class SearchResultsViewNameStreet(ListView):
    model = Street
    template_name = 'places_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Street.objects.filter(
            Q(name_street__icontains=query)
        )
        return object_list



def home(request):
    object = Place.objects.all()
    form = PlaceFilterForm(request.GET or None)

    if form.is_valid():
        places = form.filter_places()
    else:
        places = Place.objects.all()


    context = {
        'form': form,
        'places': places,
        'objects': [{'id': obj.id_place} for obj in object],

    }

    return render(request, 'user_interface/home.html', context)


def restaurant_page(request, id_place):
    object = Place.objects.filter(pk=id_place)
    context = {}
    for i in object:
        context = {
            'title': i.name_place,
            'id': i.id_place,
            'number_phone': i.number_phone,
            'takeaway_food': i.takeaway_food,
            'delivery': i.delivery,
            'summer_veranda': i.summer_veranda,
            'menu_vegan': i.menu_vegan,
            'visit_pet': i.visit_pet,
            'bus_lunch': i.bus_lunch,
            'child_room': i.child_room,
            'url': i.url,
            'live_music': i.live_music
        }
    return render(request, 'user_interface/restaurant_page.html', context=context)


class CreateViews(LoginRequiredMixin, CreateView):
    model = Place
    fields = ['id_place', 'name_place']

    def form_valid(self, form):
        return super().form_valid(form)


def places_list(request):
    places = Place.objects.all()
    if request.GET.get('live_music'):
        places = places.filter(live_music=True)
    if request.GET.get('takeaway_food'):
        places = places.filter(takeaway_food=True)
    if request.GET.get('delivery'):
        places = places.filter(delivery=True)
    if request.GET.get('summer_veranda'):
        places = places.filter(summer_veranda=True)
    if request.GET.get('menu_vegan'):
        places = places.filter(menu_vegan=True)
    if request.GET.get('visit_pet'):
        places = places.filter(visit_pet=True)
    if request.GET.get('bus_lunch'):
        places = places.filter(bus_lunch=True)
    if request.GET.get('child_room'):
        places = places.filter(child_room=True)
    return render(request, 'user_interface/search_list.html', {'places': places})

restaurants/templates/user_interface/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'user_interface/main.css' %}">
     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    {% if title %}
        <title>Сайт о ресторанах {{ title }}</title>
    {% else %}
        <title>Сайт о ресторанах</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-blue fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="#"><i class='bx bxs-rocket bx-tada-hover'></i> Рестораны</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link " href="{% url 'home' %}">Главная</a>
              <a class="nav-item nav-link" href="#">Контакты</a>
            </div>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
            	<a class="nav-item nav-link" href="{% url 'profile' %}">Профиль</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
                <a class="nav-item nav-link" href="{% url 'booking_list1' %}">Заявки</a>
                <a class="nav-item nav-link" href="{% url 'favorites:favorites' %}">Избранное</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'register_manager' %}">Вход для менеджеров</a>
              <a class="nav-item nav-link" href="{% url 'login' %}">Вход</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Регистрация</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Разделы</h3>
            <p class='text-muted'>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Поиск ресторана: по названию</li>
                <li class="list-group-item list-group-item-light"><form action="{% url 'search_result' %}" method="get"    >
                <input name="q" type="text" placeholder="Search...">
                    <li class="list-group-item list-group-item-light">по названию улицы</li>
                    <form action="{% url 'search_street' %}" method="get">
  <input name="q" type="text" placeholder="Search...">
</form>
                    <form method="get">
                <li class="list-group-item list-group-item-light">по типу заведения</li>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Фильтровать</button>
              <li class="list-group-item list-group-item-light">по типу кухни</li>
              <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Фильтровать</button>
  </form>
              <form method="GET" action="{% url 'places_list' %}">
  <label><input type="checkbox" name="live_music" {% if request.GET.live_music %}checked{% endif %}> Живая музыка</label><br>
  <label><input type="checkbox" name="takeaway_food" {% if request.GET.takeaway_food %}checked{% endif %}> Еда на вынос</label><br>
  <label><input type="checkbox" name="delivery" {% if request.GET.delivery %}checked{% endif %}> Доставка</label><br>
  <label><input type="checkbox" name="summer_veranda" {% if request.GET.summer_veranda %}checked{% endif %}> Летняя веранда</label><br>
  <label><input type="checkbox" name="menu_vegan" {% if request.GET.menu_vegan %}checked{% endif %}> Вегетарианское меню</label><br>
  <label><input type="checkbox" name="visit_pet" {% if request.GET.visit_pet %}checked{% endif %}> Разрешены животные</label><br>
  <label><input type="checkbox" name="bus_lunch" {% if request.GET.bus_lunch %}checked{% endif %}> Бизнес-ланч</label><br>
  <label><input type="checkbox" name="child_room" {% if request.GET.child_room %}checked{% endif %}> Детская комната</label><br>
  <button type="submit">Применить</button>
</form>
              </form>


                {% if places %}
                <ul>
                {% for place in places %}
                <li><a class="article-title" href="{% url 'restaurant_page' place.id_place %}">{{ place.name }}</a></li>
                {% endfor %}
                </ul>
                {% else %}
                <p>Заведений не найдено</p>
                {% endif %}
                </form>

                </li>
              </ul>
            </p>
          </div>
        </div>
      </div>

    </main>
    <!-- Футер закреплен внизу, независимо от количества постов на странице -->
    <footer class="text-center bg-dark">
      <p><a href="#">© Сайт о ресторанах</a></p>
    </footer>

    <!-- Дополнительные скрипты JavaScript -->
    <!-- Сначала jQuery, затем Popper.js, последним Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

restaurants/templates/user_interface/base2.html
<!DOCTYPE html>
{% load static %}
<html>
<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'user_interface/main.css' %}">
     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    {% if title %}
        <title>Сайт о ресторанах {{ title }}</title>
    {% else %}
        <title>Сайт о ресторанах</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-blue fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="#"><i class='bx bxs-rocket bx-tada-hover'></i> Рестораны</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link " href="{% url 'home' %}">Главная</a>
              <a class="nav-item nav-link" href="#">Контакты</a>
            </div>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
            	<a class="nav-item nav-link" href="{% url 'profile' %}">Профиль</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
                <a class="nav-item nav-link" href="{% url 'booking_list1' %}">Заявки</a>
                <a class="nav-item nav-link" href="{% url 'favorites:favorites' %}">Избранное</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'register_manager' %}">Вход для менеджеров</a>
              <a class="nav-item nav-link" href="{% url 'login' %}">Вход</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Регистрация</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>

    <!-- Дополнительные скрипты JavaScript -->
    <!-- Сначала jQuery, затем Popper.js, последним Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

restaurants/templates/user_interface/details.html
{% extends "user_interface/base2.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{}</a>>

      </div>
      <h2 class="article-title">{{ id_place }}</h2>
      <p class="article-content">{{ name_place }}</p>
    </div>
  </article>
{% endblock content %}

restaurants/templates/user_interface/home.html
{% extends "user_interface/base.html" %}
{% block content %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" >Нажмите, чтобы перейти на страницу ресторана</a>
              <small class="text-muted"></small>
            </div>
              {% for object in objects %}
            <h2><a class="article-title" href="{% url 'restaurant_page' object.id %}">{{ object.name_place }}</a></h2>
              {% endfor %}

              {% if user.is_authenticated %}
              <form action = "{% url 'favorites:favorites' %}" method = "post">
                  {% csrf_token %}
                  {{ form.as_p }}
             <button type="submit">добавить в избранное</button>
                  </form>
                  {% for object in objects %}
                   <form action = "{% url 'booking_request:booking_id' id_place=object.id %}" method="post">
                       {% endfor %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Забронировать</button>
    </form>

              {% endif %}
             </div>
            </article>



{% endblock content %}

restaurants/templates/user_interface/places_list.html
{% extends "user_interface/base2.html" %}
{% block content %}

<article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <ul>

              <a class="mr-2" >Нажмите, чтобы перейти на страницу ресторана</a>
              <small class="text-muted"></small>
              </div>
                {% for object in places%}
              <h2><a class="article-title" href="{% url 'restaurant_page' object.id_place %}">{{ object.name_place }}</a></h2>
                {% endfor %}
              <p class="article-content"></p>
          </div>
        </article>
{% endblock content %}

restaurants/templates/user_interface/restaurant_page.html
{% extends "user_interface/base2.html" %}
{% block content %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2">Страница ресторана</a>
              <small class="text-muted"></small>
            </div>
            <h2><a class="article-title">{{ title }}</a></h2>
            <h2><a class="article-content">Номер телефона: {{ number_phone }}</a></h2>
            <p class="article-title">Живая музыка: {{ live_music }}</p>
            <p class="article-content">Еда на вынос: {{ takeaway_food }}</p>
            <p class="article-content">Доставка: {{ delivery }}</p>
            <p class="article-content">Летняя веранда: {{ summer_veranda }}</p>
            <p class="article-content">Веган меню: {{ menu_vegan }}</p>
            <p class="article-content">Можно с животными: {{ visit_pet }}</p>
            <p class="article-content">Бизнес-ланчи: {{ bus_lunch }}</p>
            <p class="article-content">Детская комната: {{ child_room }}</p>
            <h2><a class="article-content">{{ url }}</a></h2>
          </div>
        </article>

{% endblock content %}

restaurants/templates/user_interface/search_list.html
{% extends "user_interface/base2.html" %}
{% block content %}

<article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <ul>

              <a class="mr-2" >Нажмите, чтобы перейти на страницу ресторана</a>
              <small class="text-muted"></small>
              </div>
                {% for object in places%}
              <h2><a class="article-title" href="{% url 'restaurant_page' object.id_place %}">{{ object.name_place }}</a></h2>
                {% endfor %}
              <p class="article-content"></p>
          </div>
        </article>

{% endblock content %}

restaurants/templates/user_interface/search_result.html
{% extends "user_interface/base2.html" %}
{% block content %}

<article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
                <ul>

              <a class="mr-2" >Нажмите, чтобы перейти на страницу ресторана</a>
              <small class="text-muted"></small>
              </div>
                {% for object in object_list%}
              <h2><a class="article-title" href="{% url 'restaurant_page' object.id_place %}">{{ object.name_place }}</a></h2>
                {% endfor %}
              <p class="article-content"></p>
          </div>
        </article>



{% endblock content %}